# Generated by Django 5.0.3 on 2025-04-16 11:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمون'},
        ),
        migrations.AlterModelOptions(
            name='delegate',
            options={'ordering': ['-created_at'], 'verbose_name': 'مفوض', 'verbose_name_plural': 'المفوضون'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company_registration',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='authorization',
        ),
        migrations.AddField(
            model_name='customuser',
            name='commercial_registration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='السجل التجاري'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_address',
            field=models.TextField(blank=True, null=True, verbose_name='عنوان الشركة'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='حساب موثوق'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='', max_length=17, validators=[django.core.validators.RegexValidator(message="يجب إدخال رقم هاتف صحيح بصيغة: '+968XXXXXXXX'", regex='^\\+?1?\\d{9,15}$')], verbose_name='رقم الهاتف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddField(
            model_name='delegate',
            name='authorization_document',
            field=models.FileField(default='', help_text='يجب أن تكون الوثيقة موقعة ومختومة', upload_to='delegate_docs/', verbose_name='وثيقة التفويض'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delegate',
            name='authorization_number',
            field=models.CharField(default='', max_length=50, verbose_name='رقم التفويض'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delegate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delegate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الشركة'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tax_card',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='البطاقة الضريبية'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('owner', 'مالك المبنى'), ('investor', 'شركة مستثمرة'), ('tenant', 'شركة مستأجرة'), ('delegate', 'مفوض التوقيع')], max_length=10, verbose_name='نوع المستخدم'),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='end_date',
            field=models.DateField(verbose_name='تاريخ الانتهاء'),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='start_date',
            field=models.DateField(verbose_name='تاريخ البدء'),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delegate_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
