# Generated by Django 5.0.3 on 2025-04-16 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_alter_delegate_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='authorization_document',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='governorate',
            field=models.CharField(choices=[('muscat', 'مسقط'), ('dhofar', 'ظفار'), ('musandam', 'مسندم'), ('buraimi', 'البريمي'), ('dakhiliyah', 'الداخلية'), ('north_batinah', 'شمال الباطنة'), ('south_batinah', 'جنوب الباطنة'), ('north_sharqiyah', 'شمال الشرقية'), ('south_sharqiyah', 'جنوب الشرقية'), ('dhahirah', 'الظاهرة'), ('wusta', 'الوسطى')], default='', max_length=20, verbose_name='المحافظة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='موثق'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='الهاتف'),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
